package:
  name: sasktran
  version: "0.0.0"

source:
  path: ../ # this can be changed to git-url

build:
  number: 0
  binary_relocation: true
  script:
    - cmake ${CMAKE_ARGS} -H. -Bbuild_conda -G "${CMAKE_GENERATOR}" -DCMAKE_INSTALL_PREFIX=${PREFIX} -DFORCE_BOOST_STATIC=OFF -DPythonEnvironments="current" -DCMAKE_BUILD_TYPE=Release # [not win]
    - cmake ${CMAKE_ARGS}  -H. -Bbuild_conda -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%" -DFORCE_BOOST_STATIC=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON # [win]
    - cmake --build build_conda --config Release

requirements:
  build:
    - cmake >=3.5
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran')}} # [not win]
  host:
    - python {{ python }}
    - boost
    - numpy # [py!=311]
    - numpy 1.23 # [py==311]
    - libnetcdf
    - hdf5
    - yaml-cpp
    - catch2
    - openblas
    - eigen
    - zlib
  run:
    - {{ pin_compatible("numpy") }}
    - libnetcdf
    - hdf5
    - yaml-cpp
    - libopenblas
    - zlib
    - python
    - pyyaml
    - appdirs
    - boost-cpp
    - urllib3
    - xarray
    - llvm-openmp


test:
  requires:
    - netcdf4
    - pytest
    - scipy
    - zenodo_get
  commands:
    - pytest --pyargs sasktran

about:
  home: http://www.example.com
  license: MIT
  summary: "Summary in here ..."