package:
  name: sasktran
  version: "0.0.0"

source:
  path: ../ # this can be changed to git-url

build:
  number: 0
  binary_relocation: true
  script:
    - cmake ${CMAKE_ARGS} -H. -Bbuild_conda -G "${CMAKE_GENERATOR}" -DCMAKE_INSTALL_PREFIX=${PREFIX} -DFORCE_BOOST_STATIC=OFF -DPythonEnvironments="current" -DCMAKE_BUILD_TYPE=Release # [not win]
    - cmake ${CMAKE_ARGS} -H. -Bbuild_conda -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%" -DFORCE_BOOST_STATIC=OFF -DCMAKE_BUILD_TYPE=Release # [win]
    - cmake --build build_conda --config Release
    - pip install sasktran --no-deps -f wheelhouse/

requirements:
  build:
    - cmake >=3.5
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran')}} # [not win]
  host:
    - python {{ python }}
    - boost
    - numpy # [py!=311]
    - numpy 1.23 # [py==311]
    - libnetcdf
    - yaml-cpp
    - catch2
    - openblas
    - zlib
  run:
    - {{ pin_compatible("numpy") }}
    - libnetcdf
    - yaml-cpp
    - openblas
    - zlib
    - python


about:
  home: http://www.example.com
  license: MIT
  summary: "Summary in here ..."