
/*-----------------------------------------------------------------------------
 *					CLIMATOLOGY_HANDLE									2005-6-24*/
/** \ingroup Climatology
 *	A structure used to uniquely identify different climatology parameters.
 *	The use of a GUID is perhaps a little overkill but on the other hand it does
 *	permit the use of new parameters in new models that users can create themselves
 *	without requiring central coordination with other developers.
 **/
/*---------------------------------------------------------------------------*/

typedef GUID CLIMATOLOGY_HANDLE;
#define EMISSION_HANDLE CLIMATOLOGY_HANDLE

#if defined(SWIG)
#define EXTERNSWIG extern const
#else
#define EXTERNSWIG extern
#endif

//EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CH3BR_CM3;
//EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CH3CL_CM3;
//EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CH4_CM3;
//EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CO2_VMR;
//EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CO_CM3;
//EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_H2O_CM3;
//EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_NH3_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_AOA_DAYS;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_AEROSOLDUST_CM3;				//!< Dust aerosol density in particles per cubic centimeter.
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_AEROSOLH2SO4_CM3;				//!< H2SO4 Aerosol density in particles per cubic centimeter.
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_AEROSOLICE_CM3;				//!< Ice aerosol density in particles per cubic centimeter
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_AEROSOLSURFACEAREA_UM2PerCM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_AEROSOLWATER_CM3;				//!< Water aerosol density in particles per cubic centimeter.
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_AEROSOL_CM3;					//!< Aerosol density in particles per cubic centimeter.
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_AEROSOL_EXTINCTIONPERKM;		//!< Aerosol in extinction per km.
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_AIRNUMBERDENSITY_CM3;			//!< Air number density, number per cubic centimeter
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_ALBEDO;						//!< Albedo value
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_Ar_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_BCPI;							// Black Carbon
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_BCPO;							// Black Carbon
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_BRCL_CM3;	 
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_BRNO3_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_BRO_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_BRO_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_BRX_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_BRX_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_BRY_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_BRY_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_BR_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_C2H2_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_C2H4_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_C2H6_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_C3H6O_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_C3H6O_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_C5H8_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_C5H8_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CCL4_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CCL4_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CF2CL2_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CF2CL2_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CF4_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CFCL3_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CFCL3_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CH2O_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CH2O_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CH3BR_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CH3BR_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CH3CL_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CH3CL_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CH3CN_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CH3I_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CH3I_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CH3OH_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CH4_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CH4_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CL2O2_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CL2_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CLNO3_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CLONO2_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CLOUD_FRACTION;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CLO_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CLY_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CLY_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CL_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CO2_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CO2_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_COF2_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CO_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_CO_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_DUST_0p7mu;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_DUST_1p4mu;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_DUST_2p4mu;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_DUST_4p5mu;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_DUST_4p5mu;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_EFFECTIVESIZE_MICRONS;			//!< Climatology of aerosol/ice effective size, (De)
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_EPV;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_GEOMETRIC_HEIGHT;					// Geometric height. This is provided to support GCM climatology code
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_GEOPOTENTIAL_HEIGHT;				// Geopotential height. This is provided to support GCM climatology code
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_H2CO_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_H2O2_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_H2O_CM3;							//!< Water Vapour number density in number per cuboc cenimenter.
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_H2O_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_H2S_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_H2_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_H2_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_HBR_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_HCL_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_HCN_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_HCOOH_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_HF_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_HI_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_HNO2_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_HNO2_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_HNO3_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_HNO3_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_HNO4_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_HO2_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_HOBR_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_HOCL_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_H_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_He_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_ICE_CM3;							//!< Ice crystal number density in particles per cubic centimeter.
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_JH2O;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_LOGNORMAL_MODERADIUS_MICRONS;		//!< Climatology of aerosol log-normal mode radius
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_LOGNORMAL_MODEWIDTH;				//!< Climatology of aerosol log-normal mode width
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_MECL_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_MECL_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_N2O5_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_N2O_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_N2O_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_N2_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_N2_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_NH3_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_NH3_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_NITS;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_NO2_CM3;					//!< NO2 number density in number per cubic centimeter
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_NO2_VMR;					//!< NO2 density as a volume mixing ratio (absolute number no PPM stuff)
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_NO3_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_NOPLUS_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_NOY_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_NOY_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_NO_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_NO_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_N_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_O2_CM3;					//!< Oxygen molecule number density (provide by MSIS 90)
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_O2_O2_CM6;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_O2_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_O3_CM3;					//!< Ozone number density in number per cubic centimeter
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_O3_VMR;					//!< Ozone number density as a volume mixing ratio
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_OCLO_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_OCPI;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_OCPO;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_OCS_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_OH_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_O_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_PAN_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_PAN_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_PH3_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_POTENTIAL_TEMPERATURE_K;			//!< Air Potential Temperature in kelvins
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_PRESSURE_PA;				//!< Air Pressure in Pascals
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_QI_MMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_QL_MMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_QV;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_RH;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_ROOH_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_ROO_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_SALA;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_SALC;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_SF6_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_SO2_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_SO2_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_SO4_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_SO4_VMR;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_SURFACE_GEOMETRIC_HEIGHT;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_SURFACE_GEOPOTENTIAL_HEIGHT;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_SURFACE_PRESSURE_PA;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_TEMPERATURE_K;				//!< Air temperature in kelvins
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_UNDEFINED;			//!< An Undefined climatology, not for general usage
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_XXX_CM3;
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_XXX_VMR;

EXTERNSWIG  EMISSION_HANDLE		SKEMISSION_PHOTOCHEMICAL_0;
EXTERNSWIG  EMISSION_HANDLE		SKEMISSION_PHOTOCHEMICAL_1;
EXTERNSWIG  EMISSION_HANDLE		SKEMISSION_PHOTOCHEMICAL_2;
EXTERNSWIG  EMISSION_HANDLE		SKEMISSION_PHOTOCHEMICAL_3;
EXTERNSWIG  EMISSION_HANDLE		SKEMISSION_PHOTOCHEMICAL_4;
EXTERNSWIG  EMISSION_HANDLE		SKEMISSION_PHOTOCHEMICAL_5;
EXTERNSWIG  EMISSION_HANDLE		SKEMISSION_PHOTOCHEMICAL_6;
EXTERNSWIG  EMISSION_HANDLE		SKEMISSION_PHOTOCHEMICAL_7;
EXTERNSWIG  EMISSION_HANDLE		SKEMISSION_PHOTOCHEMICAL_8;
EXTERNSWIG  EMISSION_HANDLE		SKEMISSION_PHOTOCHEMICAL_9;
EXTERNSWIG  EMISSION_HANDLE		SKEMISSION_PHOTOCHEMICAL_O2;
EXTERNSWIG  EMISSION_HANDLE		SKEMISSION_PHOTOCHEMICAL_OH;
EXTERNSWIG  EMISSION_HANDLE		SKEMISSION_PHOTOCHEMICAL_O3;
EXTERNSWIG  EMISSION_HANDLE		SKEMISSION_THERMAL;


// deprecated values, Dont use in new code.
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_AEROSOL_CM3_MODE2;					//!< Aerosol density coarse mode in particles per cubic centimeter.
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_GAMMA_EFFECTIVERADIUS_MICRONS;		//!< Climatology of aerosol/ice gamma effective radius
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_GAMMA_EFFECTIVEVARIANCE_PERMICRON;	//!< Climatology of aerosol/ice gamma rate
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_AEROSOL_MODERADIUS_MICRONS;	//!< Climatology of Aerosol mode radius
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_AEROSOL_MODEWIDTH;			//!< Climatology of Aerosol mode width
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_AEROSOL_CM3_MODE2;			//!< Aerosol density in particles per cubic centimeter.
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_ICE_MODERADIUS_MICRONS;		//!< Climatology of ice crystal effective radius
EXTERNSWIG  CLIMATOLOGY_HANDLE		SKCLIMATOLOGY_ICE_MODEWIDTH;				//!< Climatology of ice crystal effective width



#if !defined(SWIG)
bool operator < ( const CLIMATOLOGY_HANDLE& a,  const CLIMATOLOGY_HANDLE& b);

/*-----------------------------------------------------------------------------
 *					GlobalClimatologyHandleTable		 2015- 11- 19*/
/** **/
/*---------------------------------------------------------------------------*/

struct GlobalClimatologyHandleTable
{
	const char*				name;
	CLIMATOLOGY_HANDLE		handle;
};

#endif

bool AddGlobalClimatologyHandle ( const char* name, const CLIMATOLOGY_HANDLE&  handle);
CLIMATOLOGY_HANDLE* FindGlobalClimatologyHandle ( const char* name, bool printerror = true );
const char* FindGlobalClimatologyNameOfHandle( CLIMATOLOGY_HANDLE& handle);
bool HasKey_InGlobalClimatologyHandle( const char* name);
std::map<nxString, CLIMATOLOGY_HANDLE>* InternalGlobalClimatologyHandleTable();

bool AddGeneratedGlobalClimatologyHandleIfNotExists(const char* name);

bool SetParentHandleTable(std::map<nxString, CLIMATOLOGY_HANDLE>* parenttable);