#!/bin/bash

PYENV=$1
export SASKTRAN_IF_INCLUDE_PATH=$2
export SASKTRAN_IF_LIBRARY_PATH=$3
export CC=$4
export CXX=$5
AUDITWHEEL=$6


if [[ -z $CONDA_BUILD_STATE ]]; then

  if [[ -z $IN_MANYLINUX_CONTAINER ]]; then

      if [ $PYENV == "current" ]; then
          pushd pysasktran
          python3 -m pip wheel . -w ../wheelhouse --no-deps --no-build-isolation
          popd

      else
          eval "$(conda shell.bash hook)"
          conda activate $PYENV

          pushd pysasktran
          python3 -m pip install setuptools-scm
          python3 -m pip wheel . -w ../wheelhouse --no-deps --no-build-isolation -vvv
          popd
          conda deactivate
      fi
  else
    pushd pysasktran
    /opt/python/$PYENV/bin/python -m pip install setuptools-scm
    /opt/python/$PYENV/bin/python -m pip wheel . -w ../wheelhouse --no-deps --no-build-isolation -vvv
    popd
  fi
else
  pushd pysasktran
  $PYTHON -m pip install . --no-deps
  popd
fi




