name: 'Build, Test, and Upload Conda Packages'

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


env:
  IN_CONDA_BUILD: true

jobs:
  build-conda:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-11]
        py_version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Conda build environment 
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: conda_build
          environment-file: buildscripts/conda-build-env.yml
          channels: conda-forge
          auto-activate-base: false

      - name: Build Conda package
        shell: bash -el {0}
        run: |
          conda-build --python ${{ matrix.py_version }} -c conda-forge conda-recipe

      - name: Save conda package
        uses: actions/upload-artifact@v3
        with:
          name: conda-mac-arm-${{ matrix.py_version }}
          path: /usr/local/miniconda/envs/conda_build/conda-bld/osx-64
  
  build-conda-cross-mac-arm:
    runs-on: macos-11

    strategy:
      fail-fast: false
      matrix:
        py_version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Conda build environment 
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: conda_build
          environment-file: buildscripts/conda-build-env.yml
          channels: conda-forge
          auto-activate-base: false

      - name: Build Conda package
        shell: bash -el {0}
        run: |
          conda-build --python ${{ matrix.py_version }} -c conda-forge conda-recipe -m conda-recipe/osx_arm64_.yaml

      - name: Save conda package
        uses: actions/upload-artifact@v3
        with:
          name: conda-mac-arm-${{ matrix.py_version }}
          path: /usr/local/miniconda/envs/conda_build/conda-bld/osx-64