name: 'Codestyle Checks'

on:
  workflow_dispatch:
  push:
  pull_request:


jobs:
  build-cpp-wheels-manylinux2014:
    runs-on: ubuntu-latest
    container: continuumio/anaconda3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: pycodestyle checks
        run: |
          cd pysasktan
          pip install pycodestyle
          pycodestyle sasktran

