name: 'Sphinx Documentation Build'

on:
  workflow_dispatch:
  push:
  pull_request:


jobs:
  test-wheels-linux:
    needs: build-cpp-wheels-manylinux2014
    runs-on: ubuntu-latest
    container: continuumio/anaconda3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download wheel artifacts 
        uses: actions/download-artifact@v3
        with:
          name: wheels-linux
          path: wheelhouse

      - name: Install Make
        run: |
          apt update
          apt install make -y

      - name: Build Sphinx Docs
        run: |
          cd pysasktran
          conda env create --file docs/environment.yml
          source activate doc_env
          pip install sasktran -f ../wheelhouse/
          mkdir -p ~/.config/sasktran/ && cp ci/config.yml ~/.config/sasktran/
          python dummy_install.py
          cd docs
          make html
          cd ..
          cd ..
      