name: 'mac Build'

on:
  workflow_dispatch:
  push:
  pull_request:


jobs:
  build-cpp-wheels-mac:
    runs-on: macos-11
    env:
        BUILDPYTHONENV: "py38"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Conda build environment 
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: build_py38
          environment-file: buildscripts/mac-ci-envs/build-py38.yml
          auto-activate-base: false

      - run: | 
          conda activate
          echo $CMAKE_ARGS
          echo ${CMAKE_ARGS}
          cmake -S . -B build ${CMAKE_ARGS} -DPythonEnvironments="$BUILDPYTHONENV" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$CMAKE_INSTALL_PREFIX
      - run: cmake --build build --config Release --target install

      - name: Save wheel artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels-mac
          path: wheelhouse

      - name: Save cpp artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cpp-mac
          path: deps
