name: 'mac Build'

on:

jobs:
  build-cpp-wheels-mac:
    runs-on: macos-11
    env:
        BUILDPYTHONENV: "py38"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Conda build environment 
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: build_py38
          environment-file: buildscripts/mac-ci-envs/build-py38.yml
          channels: conda-forge
          auto-activate-base: false

      - name: configure cmake project
        shell: bash -el {0}
        run: | 
          cmake -S . -B build ${CMAKE_ARGS} -DPythonEnvironments="$BUILDPYTHONENV" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$CMAKE_INSTALL_PREFIX -DFORCE_BOOST_STATIC=OFF
      - name: build cpp
        shell: bash -el {0}
        run: cmake --build build --config Release --target install

      - name: Save wheel artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels-mac
          path: wheelhouse

      - name: Save cpp artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cpp-mac
          path: deps
