name: 'manylinux2014 Build'

on:
  workflow_dispatch:
  push:
  pull_request:


jobs:
  build-cpp-wheels-manylinux2014:
    runs-on: ubuntu-latest
    container: ghcr.io/usask-arg/sasktran-manylinux2014-build-container:main
    env:
        BUILDPYTHONENV: "cp37-cp37m;cp38-cp38;cp39-cp39;cp310-cp310;cp311-cp311"
        IN_MANYLINUX_CONTAINER: "TRUE"
        CMAKE_INSTALL_PREFIX: "/opt/sasktran/"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: cmake -S . -B build  -DPythonEnvironments="$BUILDPYTHONENV" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$CMAKE_INSTALL_PREFIX
      - run: cmake --build build --config Release --target install
      - run: cd wheelhouse
      - run: find . -name "*.whl" -type f -exec auditwheel show '{}' \;
      - run: find . -name "*.whl" -type f -exec auditwheel repair '{}' \; -exec rm '{}' \;
      - run: cd ..
      - run: ls wheelhouse/

      - name: Save wheel artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels-linux
          path: wheelhouse

      - name: Save cpp artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cpp-linux
          path: /opt/sasktran

  test-wheels-linux:
    needs: build-cpp-wheels-manylinux2014
    runs-on: ubuntu-latest
    container: continuumio/anaconda3
    strategy:
      matrix:
        py_version: [py37, py38, py39, py310, py311]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download wheel artifacts 
        uses: actions/download-artifact@v3
        with:
          name: wheels-linux
          path: wheelhouse

      - name: Test wheel
        run: bash buildscripts/test_sasktran_linux ${{ matrix.py_version }}
