name: 'manylinux2014 Build'

on:
  workflow_dispatch:
  push:
  pull_request:


jobs:
  build-cpp:
    runs-on: ghcr.io/usask-arg/sasktran-manylinux2014-build-container:main
    env:
        BUILDPYTHONENV: "cp37-cp37m;cp38-cp38;cp39-cp39;cp310-cp310;cp311-cp311"
        IN_MANYLINUX_CONTAINER: "TRUE"
    steps:
      - run: mkdir build && cd build
      - run: cmake ../ -DPythonEnvironments="$BUILDPYTHONENV" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$CMAKE_INSTALL_PREFIX
      - run: cmake --build . --config Release --target install
      - run: cd ../wheelhouse
      - run: find . -name "*.whl" -type f -exec auditwheel show '{}' \;
      - run: find . -name "*.whl" -type f -exec auditwheel repair '{}' \; -exec rm '{}' \;
      - run: mv wheelhouse/* .
      - run: rmdir wheelhouse
