name: 'Windows Build'

on:
  workflow_dispatch:
  push:
  pull_request:


jobs:
  build-cpp:
    runs-on: windows-latest
    env:
        BUILDPYTHONENV: "py37;py38;py39;py310;py311"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.1
        id: install-boost
        with:
          boost_version: 1.73.0

      - run: cmake -S . -B build  -DPythonEnvironments="$BUILDPYTHONENV" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$CMAKE_INSTALL_PREFIX
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      - run: cmake --build build --config Release --target install
