name: 'Windows Build'

on:
  workflow_dispatch:
  push:
  pull_request:


jobs:
  build-cpp:
    runs-on: windows-latest
    env:
        BUILDPYTHONENV: "py37;py38;py39;py310;py311"
        VCPKG_DEFAULT_TRIPLET: x64-windows-static

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.1
        id: install-boost
        with:
          boost_version: 1.73.0

      - name: Install netCDF
        run: vcpkg install netcdf-c

      - name: Install catch2
        run: vcpkg install catch2

      - name: Install yaml-cpp
        run: vcpkg install yaml-cpp
          

      - run: cmake -S . -B build  -DPythonEnvironments="$BUILDPYTHONENV" -DCMAKE_BUILD_TYPE=Release  -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      - run: cmake --build build --config Release --target install
