name: 'Windows Build'

on:
  workflow_dispatch:
  push:
  pull_request:


jobs:
  build-cpp:
    runs-on: windows-latest
    env:
        BUILDPYTHONENV: "py37;py38;py39;py310;py311"
        VCPKG_DEFAULT_TRIPLET: x64-windows-static-md

    steps:
      - name: Download Boost
        run: |
          curl -L -o boost.exe https://boostorg.jfrog.io/artifactory/main/release/1.82.0/binaries/boost_1_82_0-msvc-14.2-64.exe

      - name: Install Boost
        run: |
          ./boost.exe /sp- /verysilent /suppressmsgboxes /norestart /dir="c:/local/boost_1_82_0" | more

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Create Conda py38 Build Environment
        run: conda create -n py38 python=3.8 numpy=1.11.3

      - name: Install netCDF
        run: vcpkg install netcdf-c

      - name: Install catch2
        run: vcpkg install catch2

      - name: Install yaml-cpp
        run: vcpkg install yaml-cpp

      - name: Checkout repository
        uses: actions/checkout@v3

      - run: cmake -S . -B build  -DPythonEnvironments="py38" -DCMAKE_BUILD_TYPE=Release -DVCPKG_TARGET_TRIPLET=x64-windows-static-md  -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake
        env:
          BOOST_ROOT: C:/local/boost_1_82_0
          BOOST_LIBRARYDIR: C:/local/boost_1_82_0/lib64-msvc-14.2/
      - run: cmake --build build --config Release --target install
